### ISSUE TITLE
Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

### ISSUE THREAD

**Issue by serebryakov-av** [WebEntity/Installation-guide-for-GitLab-on-OS-X#45]
I did everything to step:

```
sudo -u git -H bash -l -c 'bundle exec rake gitlab:setup RAILS_ENV=production'
```

and got error:

```
rake aborted!
Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/connection_specification.rb:190:in `rescue in spec'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/connection_specification.rb:187:in `spec'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/connection_handling.rb:50:in `establish_connection'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/railtie.rb:127:in `block (2 levels) in <class:Railtie>'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:27:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.9/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
/Users/git/gitlab/config/environment.rb:5:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
/Users/git/gitlab/vendor/bundle/ruby/2.0.0/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
Tasks: TOP => gitlab:setup => environment
(See full trace by running task with --trace)
```

OS: Mac OS X 10.10.2. Almost fresh.

Could anybody help me with this problem?

**Comment by CiTroNaK** [comment]
Try

```
sudo su git
cd /Users/git/gitlab/
```

Then check your Ruby for Git user

```
ruby -v
```

If the version is `2.1.5`, you can continue

```
bundle install
bundle exec rake gitlab:setup RAILS_ENV=production
```

**Comment by serebryakov-av** [comment]
@CiTroNaK  
I get the same error.

**Comment by CiTroNaK** [comment]
Are you sure you using ruby in version `2.1.5`?

If yes, go back to you user

```
exit
```

And delete this folder

```
sudo rm -rf /Users/git/gitlab/vendor/bundle/ruby/2.0.0
```

Go back as `git` user (`sudo su git`) and repeat the above.

It seems you still using ruby in system version (`2.0.0`)...

**Comment by serebryakov-av** [comment]
@CiTroNaK, sorry! Missed version number...

```
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by serebryakov-av** [comment]
Now I can't resolve another problem:

```
# sudo -u git -H bash -l -c 'bundle exec rake gitlab:setup RAILS_ENV=production'
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.
```

Can anyone help me?

**Comment by CiTroNaK** [comment]
**You need to have ruby in `2.1.5` version not in `2.0.0`.**

Did you tried it in this way or not?
```
sudo su git
cd /Users/git/gitlab/
bundle install
bundle exec rake gitlab:setup RAILS_ENV=production
```

**Comment by serebryakov-av** [comment]
@CiTroNaK, yes I did.

```
bash-3.2$ bundle exec rake gitlab:setup RAILS_ENV=production
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by CiTroNaK** [comment]
Try
```
sudo su git
env
``` 

And paste the output here.

**Comment by serebryakov-av** [comment]
@CiTroNaK, all done:
```
bash-3.2$ env
SHELL=/bin/bash
TERM=xterm-256color
USER=git
SUDO_USER=serebryakov
SUDO_UID=501
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.bLNZzLOY5s/Listeners
__CF_USER_TEXT_ENCODING=0x0:7:49
USERNAME=root
LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
MAIL=/var/mail/root
PATH=/Users/git/.rbenv/shims:/usr/local/bin:/usr/local/apache-maven/apache-maven-3.2.5/bin:/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/subversion/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/serebryakov/Desktop/Conding/GitHub/imobiledevice-macosx:/Users/serebryakov/bin:/Applications/Araxis Merge.app/Contents/Utilities
PWD=/Users/git/gitlab
EDITOR=/usr/local/bin/mate -w
LANG=ru_RU.UTF-8
SHLVL=1
SUDO_COMMAND=/usr/bin/su git
HOME=/Users/git
LOGNAME=root
SUDO_GID=20
DISPLAY=/private/tmp/com.apple.launchd.pKgDgjR60r/org.macosforge.xquartz:0
_=/usr/bin/env
OLDPWD=/Users/git/gitlab/libiconv-1.13.1
```

**Comment by serebryakov-av** [comment]
I found a solution :) It is necessary to install the "OS X Server".

**Comment by wxm7075** [comment]
share

**Comment by wxm7075** [comment]
@serebryakov-av I can't resolve this problem, could u help me with this problem?

**Comment by serebryakov-av** [comment]
@wxm7075, do you still need help?

**Comment by morph3ux** [comment]
@serebryakov-av What was the solution?

**Comment by serebryakov-av** [comment]
@morph3ux I my case I just install the "OS X Server". I missed it at beginning.

**Comment by Tom10010** [comment]
i have the same problem now
