### ISSUE TITLE
NoMethodError: undefined method `container_registry_enabled=' for #<Project:0x007fbd0b9c2af0>'`

### ISSUE THREAD

**Issue by cyl19910101** [WebEntity/Installation-guide-for-GitLab-on-OS-X#68]
Hi there, I was trying to upgrade gitlab from 8-5 to 8-8 today, after running bundle exec rake gitlab:env:info RAILS_ENV=production, I've got an error : 
```
System information
System:
Current User:   git
Using RVM:      no
Ruby Version:   2.1.8p440
Gem Version:    2.6.4
Bundler Version:.
Rake Version:   10.5.0
Sidekiq Version:4.1.2
rake aborted!
NoMethodError: undefined method `container_registry_enabled=' for #<Project:0x007fbd0b9c2af0>
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/default_value_for-3.0.1/lib/default_value_for.rb:178:in `block in set_default_values'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/default_value_for-3.0.1/lib/default_value_for.rb:154:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/default_value_for-3.0.1/lib/default_value_for.rb:154:in `set_default_values'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:228:in `call'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `call'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `block in call'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `call'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_initialize_callbacks'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/core.rb:284:in `initialize'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/default_value_for-3.0.1/lib/default_value_for.rb:142:in `initialize'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/state_machines-activerecord-0.3.0/lib/state_machines/integrations/active_record.rb:454:in `initialize'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:61:in `new'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:61:in `new'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/reflection.rb:141:in `build_association'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/association.rb:250:in `build_record'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:146:in `build'
/Users/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:259:in `build'
/Users/git/gitlab/lib/tasks/gitlab/info.rake:33:in `block (3 levels) in <top (required)>'
/Users/git/.rbenv/versions/2.1.8/bin/bundle:22:in `load'
/Users/git/.rbenv/versions/2.1.8/bin/bundle:22:in `<main>'
Tasks: TOP => gitlab:env:info
(See full trace by running task with --trace)
'
```

I'm not familiar with ruby on rails, I've tried to remove all gems and reinstall them, but there's still this error, and I can not get a solution from google. Do you have ideas to solve this error? Thanks a lot in advance!

**Comment by CiTroNaK** [comment]
You should upgrade from 8.5 to 8.6 then to 8.7 and so on... See https://github.com/gitlabhq/gitlabhq/tree/master/doc/update
