### ISSUE TITLE
I cant push new file .....:)  but can  push a exist git lib ....

### ISSUE THREAD

**Issue by cooliean** [WebEntity/Installation-guide-for-GitLab-on-OS-X#73]
<img width="693" alt="qq20161229-0 2x" src="https://cloud.githubusercontent.com/assets/4754617/21544463/19c084b8-ce0a-11e6-8094-b9c3190a3ada.png">

<img width="650" alt="qq20161229-1 2x" src="https://cloud.githubusercontent.com/assets/4754617/21544531/b03d1bea-ce0a-11e6-92cb-53b53b026565.png">

Thank you

when i push a new file 

something error like this 

```
** [Raven] Raven 2.0.2 configured not to capture errors.
Started GET "/Cooliean/gittest.git/info/refs?service=git-receive-pack" for 10.1.1.1 at 2016-12-29 17:28:55 +0800
Processing by Projects::GitHttpController#info_refs as */*
  Parameters: {"service"=>"git-receive-pack", "namespace_id"=>"Cooliean", "project_id"=>"gittest.git"}
Filter chain halted as :authenticate_user rendered or redirected
Completed 401 Unauthorized in 158ms (Views: 18.7ms | ActiveRecord: 3.6ms)
Started GET "/Cooliean/gittest.git/info/refs?service=git-receive-pack" for 10.1.1.1 at 2016-12-29 17:28:56 +0800
Processing by Projects::GitHttpController#info_refs as */*
  Parameters: {"service"=>"git-receive-pack", "namespace_id"=>"Cooliean", "project_id"=>"gittest.git"}
Filter chain halted as :authenticate_user rendered or redirected
Completed 401 Unauthorized in 82ms (Views: 0.3ms | ActiveRecord: 2.2ms)
Started GET "/Cooliean/gittest.git/info/refs?service=git-receive-pack" for 10.1.1.1 at 2016-12-29 17:28:56 +0800
Processing by Projects::GitHttpController#info_refs as */*
  Parameters: {"service"=>"git-receive-pack", "namespace_id"=>"Cooliean", "project_id"=>"gittest.git"}
Completed 200 OK in 365ms (Views: 0.5ms | ActiveRecord: 11.0ms)
Started POST "/Cooliean/gittest.git/git-receive-pack" for 10.1.1.1 at 2016-12-29 17:28:56 +0800
Processing by Projects::GitHttpController#git_receive_pack as application/x-git-receive-pack-result
  Parameters: {"namespace_id"=>"Cooliean", "project_id"=>"gittest.git"}
Completed 200 OK in 140ms (Views: 0.2ms | ActiveRecord: 4.6ms)
Started POST "/api/v3/internal/allowed" for 192.168.31.88 at 2016-12-29 17:28:57 +0800

RuntimeError (Got a non-zero exit code while calling out to `git rev-list` in the force-push check.):
  /Users/git/gitlab/lib/gitlab/checks/force_push.rb:16:in `force_push?'
  /Users/git/gitlab/lib/gitlab/checks/change_access.rb:72:in `forced_push?'
  /Users/git/gitlab/lib/gitlab/checks/change_access.rb:30:in `protected_branch_checks'
  /Users/git/gitlab/lib/gitlab/checks/change_access.rb:15:in `exec'
  /Users/git/gitlab/lib/gitlab/git_access.rb:107:in `change_access_check'
  /Users/git/gitlab/lib/gitlab/git_access.rb:98:in `block in user_push_access_check'
  /Users/git/gitlab/lib/gitlab/changes_list.rb:12:in `each'
  /Users/git/gitlab/lib/gitlab/changes_list.rb:12:in `each'
  /Users/git/gitlab/lib/gitlab/git_access.rb:97:in `user_push_access_check'
  /Users/git/gitlab/lib/gitlab/git_access.rb:57:in `push_access_check'
  /Users/git/gitlab/lib/gitlab/git_access.rb:39:in `check'
  /Users/git/gitlab/lib/api/internal.rb:42:in `block (2 levels) in <class:Internal>'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:59:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:59:in `block (2 levels) in generate_api_method'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:58:in `block in generate_api_method'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:264:in `block in run'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:238:in `run'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:310:in `block in build_stack'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/base.rb:30:in `call!'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/base.rb:23:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/base.rb:30:in `call!'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/base.rb:23:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-oauth2-1.2.3/lib/rack/oauth2/server/resource.rb:20:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-oauth2-1.2.3/lib/rack/oauth2/server/resource/bearer.rb:8:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/error.rb:34:in `block in call!'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/error.rb:33:in `catch'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/error.rb:33:in `call!'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/middleware/base.rb:23:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:222:in `call!'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/endpoint.rb:216:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/router/route.rb:68:in `exec'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/router.rb:71:in `block in identity'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/router.rb:92:in `transaction'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/router.rb:67:in `identity'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/router.rb:52:in `block in call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/router.rb:115:in `with_optimization'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/router.rb:51:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/api.rb:119:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/api.rb:45:in `call!'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/grape-0.18.0/lib/grape/api.rb:40:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:51:in `serve'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
  /Users/git/gitlab/lib/gitlab/middleware/multipart.rb:93:in `call'
  /Users/git/gitlab/lib/gitlab/request_profiler/middleware.rb:15:in `call'
  /Users/git/gitlab/lib/gitlab/middleware/go.rb:16:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-attack-4.4.1/lib/rack/attack.rb:107:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:38:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/lock.rb:17:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.0.2/lib/raven/integrations/rack.rb:50:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:52:in `process_client'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `load'
  /Users/git/gitlab/vendor/bundle/ruby/2.3.0/bin/unicorn_rails:22:in `<top (required)>'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
  /Users/git/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
  /Users/git/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
  /Users/git/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
```

**Comment by cooliean** [comment]
I  know :);
the master branch is protected ~
